# Computer Programming For the Liberal Arts

## Michael Zelaya

## Programming Assignment 8 (Version 8)

## Spring 2023

### A)

In [1]:
import numpy as np
x= [10,20,30,40]
x1= np.array(x)
x1.resize(2,2)
x1

array([[10, 20],
       [30, 40]])

In [2]:
x2= np.add(x1,100)
x2

array([[110, 120],
       [130, 140]])

In [3]:
x3= np.multiply(x1,5)
x3

array([[ 50, 100],
       [150, 200]])

In [4]:
x4= np.sqrt(x1)
x4

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

### B)

In [6]:
x6= np.arange(3,30,3)
x6.resize(3,3)
print(x6)

x7= np.arange(10,20,10/9)
x7.resize(3,3)
print(x7)

x8=np.multiply(x6,x7)
print(x8)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[10.         11.11111111 12.22222222]
 [13.33333333 14.44444444 15.55555556]
 [16.66666667 17.77777778 18.88888889]]
[[ 30.          66.66666667 110.        ]
 [160.         216.66666667 280.        ]
 [350.         426.66666667 510.        ]]


### C)

In [7]:
x01=np.load('process1.npy')
x02=np.load('process2.npy')
x03=np.load('process3.npy')
x04=np.load('process4.npy')
x05=np.load('process5.npy')

In [8]:
array_1=np.vstack([x01,x02,x03,x04,x05])

In [10]:
print(array_1)
a,b,c,d,e=np.hsplit(array_1,5)
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())
print(e.mean())

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]
72.0
27.8
45.6
12.0
47.8
